Update Artifactory URL
LabKey/server pull request #278
Opened 2022-07-19 20:59 UTC by labkey-ians

#### Rationale
Artifactory migration

#### Related Pull Requests
* TBD

#### Changes
* Update artifactory url gradle proerty

2022-07-19 21:27 UTC, labkey-tchad requested changes
Need to remove some comments

2022-07-19 23:16 UTC, labkey-susanh requested changes

2022-07-19 23:16 UTC, labkey-susanh commented on gradle.properties
> +#artifactory_contextUrl=https://artifactory-redirect.labkey.com/artifactory
Please remove

2022-07-19 23:16 UTC, labkey-susanh commented on settings.gradle
> +//        mavenCentral()
Please remove

2022-07-20 13:59 UTC, labkey-susanh approved these changes

2022-07-20 21:22 UTC, labkey-tchad approved these changes

2022-07-20 23:28 UTC, merged