Use library substitution to prevent Eigenbase conflicts
LabKey/server pull request #551
Opened 2023-08-18 22:37 UTC by labkey-ians

#### Rationale
Use substitution option to prevent library conflicts

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/4681

#### Changes
* change from conflict exclusion to substitution

2023-08-18 22:53 UTC, labkey-jeckels reviewed
I'll defer to Susan on the full approval and recommended way to reference the old variant

2023-08-18 22:53 UTC, labkey-jeckels commented on build.gradle
> +                        substitute module('eigenbase:eigenbase-properties:1.1.2') using module("net.hydromatic:eigenbase-properties:${eigenbasePropertiesVersion}")
Do we need the version number on the old coordinates or can we drop them?

2023-08-21 13:59 UTC, labkey-susanh requested changes

2023-08-21 13:59 UTC, labkey-susanh commented on build.gradle
> +                        substitute module('eigenbase:eigenbase-properties:1.1.2') using module("net.hydromatic:eigenbase-properties:${eigenbasePropertiesVersion}")
The version number is not required from Gradle, so the version is needed only if we think a substitution of some older or new version with `net.hyromatic` library would cause problems. I'm guessing the older coordinates have been abandoned, but can't find any text that actually says that. I think removing the version should be safe. We can restore it if needed.

2023-08-21 13:59 UTC, labkey-susanh commented on gradle.properties
> +eigenbaseXomVersion=1.3.6
Looks like there's also a 1.3.7 version of eigenbase-xom, with fewer CVEs.

2023-08-21 18:55 UTC, labkey-susanh approved these changes

2023-08-21 21:03 UTC, merged