add additivity=false to prevent double logging
LabKey/server pull request #843
Opened 2024-07-02 18:07 UTC by labkey-willm

#### Rationale
the <Root level="info"> block at the start of the Loggers could cause the subsequent calls to create double logs. Setting additivity="false" will prevent that.

https://logging.apache.org/log4j/2.x/manual/configuration.html#Additivity

#### Related Pull Requests
* https://github.com/LabKey/Dockerfile/pull/97
* https://github.com/LabKey/syseng-chef-server/pull/537

#### Changes
*

2024-07-03 18:36 UTC, labkey-adam commented
I'm not an `additivity` expert by any means, but are you sure these parameters are needed here? My reading of the docs says this is useful only when a `Logger` element specifies an appender and we want its logging to go to just that appender (not the root as well). Most of these Logger elements don't specify an appender. They are present to provide the option (typically during development) of lowering the logging level for specific packages OR to raise the level for noisy third-party libraries. I don't see why we'd need `additivity` for these.

2024-07-03 18:38 UTC, labkey-adam commented
There are only three `Logger` elements here that specify an appender; I'll comment directly on those lines.

2024-07-03 18:40 UTC, labkey-adam commented on server/embedded/src/main/resources/log4j2.xml
> +        <Logger name="org.labkey.audit.event" additivity="false" level="OFF">
I'm not super familiar with this logger, but clearly the intent is to log to both LABKEY_AUDIT and CONSOLE. I would remove both `additivity` and the CONSOLE ref, which should be the equivalent.

2024-07-03 18:41 UTC, labkey-adam commented on server/embedded/src/main/resources/log4j2.xml
> +        <Logger name="org.labkey.core.admin.AdminController.ContentSecurityPolicyReportAction" additivity="false" level="warn">
Removing `additivity` and the CONSOLE AppenderRef should give us both console and CSP_REPORT logging.

2024-07-03 18:42 UTC, labkey-adam requested changes
See comments

2024-07-03 18:42 UTC, labkey-adam commented on server/embedded/src/main/resources/log4j2.xml
> +        <Logger name="org.labkey.api.script.ScriptService.Console" additivity="false" level="info">
Not sure, but I think we probably want logging to the console as well, which suggests removing additivity.

2024-07-03 18:53 UTC, labkey-adam commented
I see now that a couple of these `additivity` parameters were already present (not added in this PR). Comments still hold, though... `additivity` plus CONSOLE appender seems unnecessary.

2024-07-03 18:57 UTC, labkey-adam commented
> I'm not an `additivity` expert by any means, but are you sure these parameters are needed here? My reading of the docs says this is useful only when a `Logger` element specifies an appender and we want its logging to go to just that appender (not the root as well). Most of these Logger elements don't specify an appender. They are present to provide the option (typically during development) of lowering the logging level for specific packages OR to raise the level for noisy third-party libraries. I don't see why we'd need `additivity` for these.



> I'm not an `additivity` expert by any means, but are you sure these parameters are needed here? My reading of the docs says this is useful only when a `Logger` element specifies an appender and we want its logging to go to just that appender (not the root as well). Most of these Logger elements don't specify an appender. They are present to provide the option (typically during development) of lowering the logging level for specific packages OR to raise the level for noisy third-party libraries. I don't see why we'd need `additivity` for these.

This is the very first scenario cited on the doc page as an example where `additivity` is not needed: https://logging.apache.org/log4j/2.x/manual/configuration.html#Additivity

2024-07-03 20:42 UTC, labkey-willm commented
> > I'm not an `additivity` expert by any means, but are you sure these parameters are needed here? My reading of the docs says this is useful only when a `Logger` element specifies an appender and we want its logging to go to just that appender (not the root as well). Most of these Logger elements don't specify an appender. They are present to provide the option (typically during development) of lowering the logging level for specific packages OR to raise the level for noisy third-party libraries. I don't see why we'd need `additivity` for these.
> 
> This is the very first scenario cited on the doc page as an example where `additivity` is not needed: https://logging.apache.org/log4j/2.x/manual/configuration.html#Additivity

yes, you're quite right, and this confirms what we just found with the chef version, is that having additivity=false on loggers w/o specific appenders results in no logs at all for that logger. I'll fix things up.

2024-07-04 00:03 UTC, labkey-adam requested changes
A couple remaining tweaks

2024-07-04 00:03 UTC, labkey-adam commented on server/embedded/src/main/resources/log4j2.xml
> +        <Logger name="org.labkey.core.admin.ActionsTsvWriter" level="info">
I think `additivity="false"` is intentional here; we want this logging to go to a separate file but not CONSOLE/LABKEY.

2024-07-04 00:03 UTC, labkey-adam commented on server/embedded/src/main/resources/log4j2.xml
> +        <Logger name="org.labkey.api.data.queryprofiler.QueryProfiler.QueryProfilerThread" level="info">
I think `addivitity="false"` is intentional here as well

2024-07-04 00:03 UTC, labkey-adam commented on server/embedded/src/main/resources/log4j2.xml
> +        <Logger name="NoOpLogger" level="OFF" />
I don't know who added this or why, but guessing that `addivitity="false"` is intentional

2024-07-08 22:01 UTC, labkey-adam approved these changes

2024-07-09 18:08 UTC, merged